### ISSUE TITLE
3D viewer

### ISSUE THREAD

**Issue by Sideghost** [Ex-Chelas/Troca-Tintas#9]
![image](https://github.com/user-attachments/assets/f74c8d13-e227-4946-a921-594af89117a5)

**Comment by Rafael4DC** [comment]
http://localhost:5173/3dViewer?color=Dark-Angels-Green

Done

When the page goes to 3dview it always goes to the master of executions model, and only sneding a differente color in color param will cahnge it. Options are the name of the folders, on uppercase with dashes
This can be used for the color picker task

even created the page for it
the two shitty side bars aree not done, left one is not doable at this point, can be done as a mock, and the right one is wholy irrelvant, just copy the way its done in the home page, and leave it at that, didnt do it, needs to be done according to design of the app
